# =============================================================================
# Immersive-Sounds-Backpack — Inventory Open/Close SFX (future-proofed)
# Rules: start simple, base-anchored, no regex, use findreplace / findreplacetrim,
#        no existence checks, no fallbacks.
# =============================================================================

# 1) Load custom backpack sounds + init suppress flag
gml_Object_obj_controller_Create_0:
  - type: append
    code: |-
      global.backpack_open_sound  = audio_create_stream("mods/audio/interface/snd_ui_backpack_open.ogg");
      global.backpack_close_sound = audio_create_stream("mods/audio/interface/snd_ui_backpack_close.ogg");
      global.__zs_suppress_inv_close_sfx = 0;

# 2) Replace the vanilla inventory-open sound (single line -> findreplace)
gml_GlobalScript_player_action_open_inventory:
  - type: findreplace
    find: |-
      audio_play_sound(snd_inventory_open, 2, false);
    code: |-
      audio_play_sound(global.backpack_open_sound, 10, false);

# 3) Gate backpack CLOSE SFX:
#    - Skip if containers flagged suppression
#    - Skip if a chest is open (container close path)
gml_GlobalScript_ui_inventory_close_all:
  - type: findreplacetrim
    find: |-
      function ui_inventory_close_all()
      {
          uiGetData().reward_item = undefined;
          uiGetData().player_got_hit = false;
          var _layer = uiOnionCurrentLayer();
    code: |-
      function ui_inventory_close_all()
      {
          uiGetData().reward_item = undefined;
          uiGetData().player_got_hit = false;

          // Only play backpack CLOSE when not suppressed AND not closing a chest UI
          if (global.__zs_suppress_inv_close_sfx || uiGetData().chest_using) {
              global.__zs_suppress_inv_close_sfx = 0;
          } else {
              audio_play_sound(global.backpack_close_sound, 10, false);
          }

          var _layer = uiOnionCurrentLayer();

# 4) Stop streams on teardown (no destroy)
gml_Object_obj_controller_CleanUp_0:
  - type: append
    code: |-
      audio_stop_sound(global.backpack_open_sound);
      audio_stop_sound(global.backpack_close_sound);
