# ZS Mod Pack – gmloader code_patch file
# Purpose: verify GMLoader pipeline + provide a safe startup hook.
# Notes: Uses the official GMLoader ImportConfigDefinedCode schema (types: findreplace, findreplacetrim, findreplaceregex, prepend, append).
# Source: https://github.com/Senjay-id/GMLoader/wiki/Modders-guide (mirrored)
# Scope: Conservative; no gameplay changes yet.

# --- Startup hook: append a tiny init snippet to the controller Create event ---
# This event name exists in ZERO Sievert (seen in crashes/logs as gml_Object_obj_controller_Create_0).
# The code is harmless: sets a global marker and prints a debug line once at startup.
# If the target script name ever changes, this patch will just be ignored.

gml_Object_obj_controller_Create_0:
  - type: append

    code: |-
      // [GMLoader] mods-here.yaml loaded (Zero Sievert – Custom Mods)
      if (!variable_global_exists("__zs_mods__")) {
          global.__zs_mods__ = 1;
          show_debug_message("[ZS Mods] gmloader pipeline OK – mods-here.yaml appended to obj_controller Create.");
      }
